### ISSUE TITLE
Understanding multimapping

### ISSUE THREAD

**Issue by tmokveld** [ekg/vg#114]
Hello,

I was exploring a bit with different settings and whatnot but I seem to have some problems understanding as to how multi-mapping scenarios are handled. For instance I made a toy set (~2500 bp) with a 110 bp repeat occurring in it three time. From this I build a graph with max node size 50, indexed it (k = 11) and mapped a sub-sequence (21 bp) of the repeat onto it.

What I saw from the results was that the sub-sequence would always map on the first instance of the repeat in the graph. In the debug mode it displayed that the other nodes in which this sub-sequence is also located became candidates for mapping. However it ends up with just a mapping on the first node that contains it. Is this because the other potential mappings are exactly the same? So that it is assigned to the first node that it encountered, and that the others are no longer considered? I guess that would explain why changing max-multimaps does not have any effect on the number of alignments that you ultimately receive.

Maybe I am missing something obvious here, so hopefully someone can fill me in on that.

Thanks

**Comment by ekg** [comment]
It should provide a series of alignments, with one arbitrarily marked as primary. If you could share the simulated set we could add it as a test case to ensure the correct behavior.

**Comment by tmokveld** [comment]
I don't know exactly how to share it so I will just put it in this comment:

FASTA:
http://pastebin.com/bhnkh2Mq

Repeat:
```
GGGTTGGATTTGGTCAGGCGCACCCTGGACGAAGCTCGTGCTGCTGCCCGCGCGCGCGGACAAGACGCCGGTCGAGGGCGGGTCGCTTCCGTTGCGTCGGGTCGGGTGGCCGGACGGCGA
```
Subsequence: 
`CTGCTGCCCGCGCGCGCGGAC`

Nodes on which repeats span:
`R1: 10-12`
`R2: 27-29`
`R3: 43-45`

Subsequence matches on:
`R1: 11`
`R2: 28`
`R3: 43-44`

Commands run:
`vg construct -r repeat3x.fa -m 50 > repeat3x.vg`
`vg index -s -k 11 repeat3x.vg`
`vg map -D -M 3 -s CTGCTGCCCGCGCGCGCGGAC repeat3x.vg -J`

**Comment by tmokveld** [comment]
For reference I did this on release `1.1.0` and on `c18a972`, with the same results.

**Comment by ekg** [comment]
It seems that the multimapping isn't happening due to the short distance between the alignment clusters.

From the debugging output:

```text
initial threads
1:
        43 
        44 

2:
        11 11 
        28 28 

threads ready for alignment
6:
        11 11 28 28 43 44 
```

So only one "thread" is used for alignment (these are approximately like smem's in bwa mem). This generates a single target graph against which the alignment is made, including the entire node range from 11-44. As a result, only one alignment is produced.

To fix this, you can use a smaller node size in construction. If I do `vg construct -r repeat3x.fa -m 16 >repeat3x.vg` and then index as before, I get this multi-mapping:

```json
{"sequence": "CTGCTGCCCGCGCGCGCGGAC", "path": {"mapping": [{"position": {"node_id": 86}, "edit": [{"from_length": 16, "to_length": 16}]}, {"position": {"node_id": 87}, "edit": [{"from_length": 5, "to_length": 5}]}]}, "score": 42}
{"sequence": "CTGCTGCCCGCGCGCGCGGAC", "is_secondary": true, "path": {"mapping": [{"position": {"node_id": 33, "offset": 8}, "edit": [{"from_length": 8, "to_length": 8}]}, {"position": {"node_id": 34}, "edit": [{"from_length": 13, "to_length": 13}]}]}, "score": 42}
{"sequence": "CTGCTGCCCGCGCGCGCGGAC", "is_secondary": true, "path": {"mapping": [{"position": {"node_id": 134, "offset": 12}, "edit": [{"from_length": 4, "to_length": 4}]}, {"position": {"node_id": 135}, "edit": [{"from_length": 16, "to_length": 16}]}, {"position": {"node_id": 136}, "edit": [{"from_length": 1, "to_length": 1}]}]}, "score": 42}
```

It looks roughly correct to me. Visualizing the alignments with `vg view -dA aln.gam repeat3x.vg` yields the expected results:

![screenshot from 2015-10-07 14 00 06](https://cloud.githubusercontent.com/assets/145425/10336822/c9f99ba6-6cfb-11e5-8e4e-a6626ed588ff.png)
![screenshot from 2015-10-07 13 59 47](https://cloud.githubusercontent.com/assets/145425/10336821/c9f9353a-6cfb-11e5-8259-1cf1cab977cf.png)
![screenshot from 2015-10-07 13 59 23](https://cloud.githubusercontent.com/assets/145425/10336823/c9fbe7a8-6cfb-11e5-8215-c228ca262e46.png)

Now, I agree that the clustering behavior is weird. The threads are being established across much larger space than I thought was normal. I'll look into this. Hopefully, this can help you get started though.

**Comment by ekg** [comment]
I'm curious what @adamnovak thinks about this as he's done most of the work for supporting multimapping.

**Comment by tmokveld** [comment]
Interesting, thanks for the quick response!

**Comment by adamnovak** [comment]
That's what I would expect to see; it can only produce one best mapping per thread, because each thread produces one subgraph against which the query is aligned with the GSSW local aligner. If the repeat copies are further apart, or if the nodes are smaller, you can get the repeats into different threads and get multiple results.

I'm not sure how/if GSSW can be induced to produce multiple disjoint mappings for a subgraph, or if we want to do that.

**Comment by ekg** [comment]
@adamnovak It could be possible to do in GSSW if we changed the traceback. We might drive ourselves crazy trying to manage the different types of multi-mapping though.

**Comment by ekg** [comment]
One problem is that `vg::Mapper::max_thread_gap`, [which defines how far apart in id space we will consider merging the threads](https://github.com/ekg/vg/blob/03ce2b8141a7edacee28d69581a6c07bdb3377f6/mapper.cpp#L777-L803), is not exposed via the command line API. It is set as 30 by default. A bit long no?

**Comment by adamnovak** [comment]
It's long for tiny test graphs, but we might need it to be a bit long in order to bridge over either deletions or bits of extra graph that have had to be shoved between the bits you really need in ID space.

It ought to have a flag, though.

**Comment by ekg** [comment]
And it's hard to make the threads if they require a context construction
from the index. That said, maybe with xg indexes this problem goes away and
we can build up the threads using different criteria, such as a graph size.
I'm not sure as I haven't tested.
