### ISSUE TITLE
node/path labelling missing after vg mod 

### ISSUE THREAD

**Issue by lexnederbragt** [ekg/vg#123]
Node and path labelling enabled like this
```
vg msga -f seq.fasta | vg view -pdn - >seq.dot
```
does not survive chopping:
```
vg msga -f seq.fasta | vg mod -u - | vg view -pdn - >seq2.dot
```
(issue resulting from discussion that ended here https://twitter.com/erikgarrison/status/654744469175058432)

**Comment by ekg** [comment]
Yup it won't survive chopping or unchopping. This is due to rushed coding
on my part.

**Comment by ekg** [comment]
To fix this, I need to ensure that the unchop only merges nodes that also have exactly the same path set. Otherwise, we need to start using the mappings to represent path relationships to the graph. This is possible but will turn into a huge pain if it becomes typical use. Divide node and unchop would then need to both handle paths embedded in the graph that do not have perfect mappings.

**Comment by ekg** [comment]
This should now work. Let me know if it doesn't!
