### ISSUE TITLE
build_gcsa - joinPaths(): Size limit exceeded, construction aborted

### ISSUE THREAD

**Issue by mlin** [ekg/vg#152]
@ekg @jltsiren I made a run at the [xg/GCSA2 whole genome indexing](https://github.com/ekg/vg/wiki/working-with-a-whole-genome-variation-graph) and got the aforementioned error from build_gcsa. I see there's a `-l` option to increase the size limit, any suggested settings? What does the limit mean?

[Full log](https://gist.github.com/mlin/5e82ef4fa7031258492f) -- you can find the exact invocations in there
[My script](https://github.com/dnanexus-rnd/dxvg/blob/xg/applets/vg_index/src/code.sh)

**Comment by mlin** [comment]
vg 1.3.0 BTW

**Comment by ekg** [comment]
Quick possible fix... Try vg mod ... -e 2. The edge bounding algorithm
changed slightly in a recent commit and the result is that this parameter
needs to be shifted down slightly to fit in under 200G. I should have
updated the instructions to match the most recent version.

If not that, I've got more questions.

**Comment by ekg** [comment]
I believe this changed in a pre 1.3 commit, but am not at a computer to
check right now.

**Comment by jltsiren** [comment]
The size limit is in gigabytes of disk space. Memory usage will be higher, because GCSA2 construction keeps various other structures in memory. On a system with 256 gigabytes of memory, the default limit of 200 GB is quite close to the maximum. You can probably increase it to 210 GB or even 220 GB, but not further than that.

GCSA2 v0.4 will change the construction algorithm completely. I'm hoping that a whole genome index can be built on a 64 GB or 128 GB system with the new algorithm, but that remains to be seen.

**Comment by mlin** [comment]
Switching to `-e 2` succeeded, I got a 25.5 GiB index, and mapped some unitigs with it!
