### ISSUE TITLE
Examples of using `vg view` / generating dot files

### ISSUE THREAD

**Issue by ryan-williams** [ekg/vg#7]
There don't seem to be any, from what I can see.

It seems like the default behavior emits GFA.

**Comment by ekg** [comment]
Here's how you output dot format:

```bash
vg view -d x.vg >x.dot
```
Every tool in `vg` is self-documenting. Just add `-h` or `--help` to the command line.

Also, any graph output can be piped into any other program. So you can pick up a tiny bit of one graph and then pipe it into `vg view` or `vg align`. For example, here we can index a graph we've made, then pick up the node with id 50 and its neighbors (defined by a BFS search with up to 5 steps):

```bash
vg index -s x.vg
vg find -n 50 -c 5 x.vg | vg view -d - | dot -Tpng -o barrio50.png
```

These should be added to the documentation. My preference is to start documenting things on the wiki.

**Comment by ryan-williams** [comment]
cool, thanks @ekg. I'm happy to add some documentation things as I play around with `vg` a bit; are you suggesting creating this repo's GitHub wiki? Do you envision the README remaining a/the main source of documentation?

Also, while we're here, any interest in making some of the unchecked boxes from the README into issues?

**Comment by ekg** [comment]
I think we should start the wiki. The readme should be shorter and more
clear so people don't get confused.

And the unchecked boxes should absolutely be issues. It hasn't been an..
Issue because its been just me for the past four months. Pick your favorite
and let's jam.

**Comment by ekg** [comment]
Have you had a chance to experiment further?

**Comment by ryan-williams** [comment]
Sorry for the radio silence, was traveling and otherwise preoccupied but have time to work on variant-graph-related things now. Beginning the "empty checkbox" -> issue migration now, wave me off if that's not a good idea!

**Comment by ekg** [comment]
No, it's great! Go for it. Will you be interested in working on development?

**Comment by ryan-williams** [comment]
Interested for sure; not sure I should commit to anything yet but if you have suggestions for pieces I could bite off easily I am all ears. I have yet to use `vg` beyond running it on its own test cases and trying to follow the GA4GH discussion around sub-graphs vs. side-graphs.

I've been thinking a lot (and coding a little) about what a good, interactive, web-based graph-viz story would look like. Can take that discussion over to #8 though.

**Comment by ekg** [comment]
The tests are there so you can see if any commits you make will break the
system, so don't be afraid to try out new ideas.

What are you interested in working on? There are obviously a number of open
tasks in vg.

The major push in the next few months will be to use a GCSA derivative for
decreasing the size of the sequence index. I see this as critical for
making adoption of this aligner tenable  Other than this, I'd like to deal
with circular genomes, to use an alignment to modify the graph (allowing
iterative construction for alignable genomes), generate a compressed
version of a sequencing dataset, and add annotations to the graph. These
seem like essential features, and if you just want to get your hands dirty
any will suit.

I am begging the GA4GH to consider the models that vg is using as a
potential interchange definition. I don't know how successful I'll be, but
I can ensure that vg is a working, practical, and well-known system. On the
standardization front, the thing to do is to provide a pull request
adjusting the GA4GH model to be congruent with vg (variation graphs, which
are sequence graphs with labeled paths). I am increasingly reticent to work
on that effort because there is not another working graph aligner/genome
implementation in the public, but hopefully this will change soon.

I'll help you work on anything you'd like to contribute. Issues are a great
and public place to discuss things, but if you need I can be reached in
realtime as well. Just email me and we can set up a time to discuss.

**Comment by ryan-williams** [comment]
That sounds good @ekg; I don't see your email here but mine is ryan.blake.williams@gmail.com if you want to shoot me a note; setting up a call or something sounds great.
