### ISSUE TITLE
use sigma.js for interactive output

### ISSUE THREAD

**Issue by ekg** [ekg/vg#8]
`vg view` should produce an interactive web view using sigma.js.

**Comment by ryan-williams** [comment]
sigma.js looks pretty cool, I'm going to try to get some of its examples up and running.

Does `vg` need to output any new format to feed into sigmajs, or can existing e.g. `dot` output work?

**Comment by ekg** [comment]
I'm not sure... Although if a new format is needed we can just add it to
`vg view`.

**Comment by ryan-williams** [comment]
@ekg I mentioned previously that I'd played around with SigmaJS and had a little trouble with it. Quick update for the record:

I was surprised by some of the default behaviors related to camera-sizing / zooming: it was not obvious to me how to override the initial [zoom out so that the entire graph fits on the screen] behavior; for example, I'd like to be able to tell it to make the `size` parameters passed to nodes correspond to pixels on the screen. After poking around a bit, I think I have an idea how to do this using [`camera.goTo`](https://github.com/jacomyal/sigma.js/blob/e264b61e634489167caa6171808787c80f339d4e/src/classes/sigma.classes.camera.js#L44-L69).

I also played with the [`dragNodes` plugin](https://github.com/jacomyal/sigma.js/blob/e264b61e634489167caa6171808787c80f339d4e/plugins/sigma.plugins.dragNodes/sigma.plugins.dragNodes.js) and was unpleasantly surprised by the default behavior where the zoom level of the whole graph is modified as a node is dragged in such a way that the screen is always the bounding-box of the entire graph. [#256](https://github.com/jacomyal/sigma.js/issues/256) and [#423](https://github.com/jacomyal/sigma.js/issues/423) both seem to be related.

I stumbled across [linkurious](https://github.com/Linkurious/linkurious.js) which has [a bunch of plugins](https://github.com/Linkurious/linkurious.js/tree/linkurious-version/plugins) that seem promising, and am digging into SigmaJS code further since I'm sure that ultimately it can be made to do what we want here.

I'd mentioned [CytoscapeJS](http://js.cytoscape.org/) as a potentially interesting alternative, but haven't gone any further in evaluating it.

I'll let you know what else I figure out.

**Comment by ekg** [comment]
I think it makes sense to close this one. We can evaluate later.
