### ISSUE TITLE
Submodules getting out of control?

### ISSUE THREAD

**Issue by glennhickey** [ekg/vg#88]
Adding xg to vg duplicates the protobuf submodule among others.  Getting to the point where downloading and building from scratch takes forever.  Any reason not to just have xg be part of vg?  Seems like it'd also be easier to maintain that way...

**Comment by ekg** [comment]
This is also bothering me, but I don't have any good solutions.

In the case of xg we can de-duplicate things by building it from vg-land rather than using its internal `Makefile`. The download still happens though, and this doesn't really resolve the problem. It's also manual and annoying. I was under the impression that we could use cmake and git submodules to sort things out, but the solutions I found were not very nice.

I put it in its own submodule so it is independent from vg except for the common protobuf definition and stream.hpp. This should keep it independent and make it easier to refactor for other purposes, such as to deal with different kinds of graphs.

Any advice or suggestions would be really welcome.

**Comment by ekg** [comment]
Also, it's a bit tricky to rely on protobuf3 and rocksdb, as these are moving targets where certain features vg needs haven't made it into any distributions. So these should probably remain submodules.

There must be a better way to regularize the build process, or cache builds somehow, so that rebuilding isn't such a nightmare. (For me 10-20 minutes from scratch on my laptop.)

However, I don't build from scratch much, only when submodules are updated and I can't get the repo into the correct state with a git pull. If only things in the vg repo change, I do `make clean-vg` and then `make`.

**Comment by glennhickey** [comment]
Yeah, it's certainly not the end of the world... I just had to gripe.  I
don't have many ideas beyond folding vg into xg. I personally could
certainly avoid many rebuilds by getting better at git (I still blow up and
redownload my repo semi regularly).

I just checked, and it seems make -j is working much better than I remember
(I'm sure it blew up right away when I tried a few months ago).  It took
two tries to build with a big j, but that's still not too bad (and could
probably be fixed easily in the makefile).  This alone will be a big help
for me...

**Comment by ekg** [comment]
I'm thinking that something like [biicode](https://www.biicode.com/) might solve things.

**Comment by ekg** [comment]
Looks like they've open sourced the necessary bits to continue even if they discontinue support: http://blog.biicode.com/biicode-open-source-client/. I'm going to go for it.

**Comment by ekg** [comment]
And... [biicode shut down in August](http://blog.biicode.com/). But as a result everything is open. The existing hosting is a temporary measure, and might be available for the next year. Ouch. Looks like I might need to get a bit lower-level with the cmake integration.

**Comment by ekg** [comment]
@edawson is working on a solution to this. Onward.

**Comment by edawson** [comment]
Alright, I've patched this up on my fork: https://github.com/edawson/vg

What I did was refactor the vg package and its submodules. It now has four main top-level directories:
```deps``` - contains all submodules, unbuilt.
```src``` - contains all vg source code (and only vg source code)
```docs``` - contains docs
```tests``` - contains tests

When you build the package, four more top-level directories are created:
```bin``` - contains protoc and the vg executable
```lib``` - contains all libraries used by vg and the vg library itself.
```include``` - contains all header files (from the dependencies) used in the vg source code.
```obj``` - contains all object files needed to compile the vg executable and library.

These directories get populated by the Makefile. To find them, the linker/compiler needs to know the path to the directories; you can modify the relevant environment variables by sourcing the ```source_me.sh``` script. To run protobuf, for example, you'll need to add the ```lib``` directory to the $LD_LIBRARY_PATH so it can find its dynamic library at runtime. You'll have to source the ```source_me.sh``` script to build and run vg (so you might want to add it to your bashrc).

Once I'd modified the makefile, I modified the submodules with new versions that follow a similar structure. VCFLIB and XG got the majority of the updates. This means that you'll need the same path modifications to build XG on its own (i.e. you'll need to have the relevant cmake, protobuf and sdsl-lite header files/executables/libs on LD_INCLUDE_PATH/PATH/LD_LIBRARY_PATH, respectively). If you wanted to build xg on its own you could also run ```make get-deps``` and ```source source_me.sh```, and build away.

To extend the vg package, you'd follow this recipe:
1. Add any new source code to ```src/```
2. Add any new dependencies' source code to a subdirectory of ```deps/```
3. Update the top-level ```.gitmodules```, if needed. Run ```git submodule sync```
4. Update the makefile with a new rule to build the dependency. The target should be a library or object file. The rule should look something like:
 ```
      ## LIB_DIR and several other directories are defined in the makefile
      ## $@ is a reserved word in Make for the target of the rule
      ## $< is a reserved work in Make for the first dependency of the rule
      $(OBJ_DIR)/new_lib.o: $(DEP_DIR)/$(NEW_LIB_DIR)/new_lib.cpp $(LIB_DIR)/libxg.a
            cd $(DEP_DIR)/ && cd $(NEW_LIB_DIR)/ && $(CXX) $(CXXFLAGS)-c  -o $@ $< && cp new_lib.o $(OBJ_DIR)/
     $(LIB_DIR)/libnew.a: $(OBJ_DIR)/new_lib.o
           ar rs $@ $<
 ```
Then just ```source source_me.sh && make -j 10 && make test``` to test your additions.

**Comment by ekg** [comment]
https://github.com/ekg/vg/pull/155 is ready to pull in. Should I do this into master first?

**Comment by ekg** [comment]
I'm not sure how I feel about the source me script... How could this be done within the makefile?

**Comment by ekg** [comment]
Ah it needs to be done for dynamic linking. But static builds should be fine, no?

**Comment by edawson** [comment]
I've tried about every Make hack I can think of, but I can't make it play without some sort of external path mods. Make doesn't seem to be able to pollute its parent shell so the environment variables don't propagate.

**Comment by ekg** [comment]
If we can get static building working, it will make it much easier to run vg and I'll finally close this issue!
